stages:
    - deploy

deploy-server:
  stage: deploy
  environment:
    name: development
    url: https://event.sertifikasiku.com/
  script:
    - sshpass -p ${SSH_KEY} ssh -oStrictHostKeyChecking=no -p ${SSH_PORT} ${SSH_LOGIN} -t "cd /var/www/html/adminlayanan && sh update.sh"
    - echo "Job-mu is sukespulll!"
  only:
    - master
